version: '3.8'

services:
  ai_service:
    image: stable-diffusion-ai
    ports:
      - "5002:5000"
    volumes:
      - ./ai_model/generated_images:/app/generated_images
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - photo-op-network

  database_service:
    build: ./database-service
    ports:
      - "5003:5003"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - DATABASE_NAME=photo_op
    depends_on:
      - mongodb
    networks:
      - photo-op-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - photo-op-network

  prometheus:
    image: prom/prometheus:latest
    container_name: photo-op-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - photo-op-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: photo-op-grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    networks:
      - photo-op-network
    depends_on:
      - prometheus
    restart: unless-stopped

networks:
  photo-op-network:
    driver: bridge

volumes:
  mongodb_data:
  prometheus_data:
  grafana_data: 